# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test suite

on: [push, pull_request]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meteor: [ '2.13.3', '3.0.4', '3.1.2' ]
    # needs: [lintcode,lintstyle,lintdocs] # we could add prior jobs for linting, if desired
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup meteor
        uses: meteorengineer/setup-meteor@v2
        with:
          meteor-release: ${{ matrix.meteor }}

      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: cd tests && meteor npm install && meteor npm run test

